# Generated by Django 6.0.2 on 2026-02-27 07:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(error_messages="Faqat o'zbekiston aloqa operatorlari qo'llab quvvatlanadi", max_length=12, unique=True, validators=[django.core.validators.RegexValidator(regex='/^998([378]{2}|(9[013-57-9]))\\d{7}$/')])),
                ('membership_level', models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro')], default='basic', max_length=5)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Balans')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='librarycard', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kutubxonachi',
                'verbose_name_plural': 'Kutubxonachilar',
            },
        ),
    ]
