# Generated by Django 6.0.2 on 2026-02-28 03:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarycard',
            name='phone',
            field=models.CharField(error_messages={'invalid': "Faqat O'zbekiston aloqa operatorlari qo'llab-quvvatlanadi.", 'unique': "Bu telefon raqam allaqachon ro'yxatdan o'tgan."}, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(regex='/^998([378]{2}|(9[013-57-9]))\\d{7}$/')]),
        ),
    ]
