# Generated by Django 6.0.2 on 2026-02-28 03:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_librarycard_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarycard',
            name='phone',
            field=models.CharField(error_messages={'invalid': "Faqat O'zbekiston aloqa operatorlari qo'llab-quvvatlanadi.", 'unique': "Bu telefon raqam allaqachon ro'yxatdan o'tgan."}, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?998(?:90|91|93|94|88|97|95|99|77|33|98)\\d{7}$')]),
        ),
    ]
