# Generated by Django 6.0.2 on 2026-02-27 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="To'liq F.I.Oni kiriting", max_length=100, verbose_name='F.I.O')),
                ('country', models.CharField(choices=[('uz', 'Uzbekistan'), ('ru', 'Russia')], db_index=True, default='uz', verbose_name='Davlat')),
                ('birth_year', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan yil")),
            ],
            options={
                'verbose_name': 'Muallif',
                'verbose_name_plural': 'Mualliflar',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
                ('slug', models.SlugField(help_text='URL uchun, masalan: my-post-title', max_length=255, unique=True, verbose_name='Slug maydoni')),
            ],
            options={
                'verbose_name': 'Janr',
                'verbose_name_plural': 'Janrlar',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, unique=True, verbose_name='Teg nomi')),
                ('slug', models.SlugField(help_text='URL uchun, masalan: my-post-title', max_length=255, unique=True, verbose_name='Slug maydoni')),
            ],
            options={
                'verbose_name': 'Teg',
                'verbose_name_plural': 'Teglar',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Kitob nomi')),
                ('description', models.TextField(verbose_name='Kitob haqida batafsil')),
                ('published_year', models.IntegerField(verbose_name='Ishlab chiqarilgan sana')),
                ('isbn', models.CharField(max_length=255, unique=True, verbose_name='Xalqaro standart kitob raqami')),
                ('language', models.CharField(choices=[('uz', 'Uz'), ('ru', 'Ru'), ('eng', 'Eng')], default='uz', max_length=10, verbose_name='Til')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Kitob narxi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitoblar', to='catalog.author', verbose_name='Muallif')),
                ('genres', models.ManyToManyField(related_name='kitoblar', to='catalog.genre', verbose_name='Janr')),
                ('tags', models.ManyToManyField(related_name='kitoblar', to='catalog.tag', verbose_name='Teg')),
            ],
            options={
                'verbose_name': 'Kitob',
                'verbose_name_plural': 'Kitoblar',
            },
        ),
    ]
