# Generated by Django 6.0.2 on 2026-02-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('uz', "O'zbek tili"), ('ru', 'Rus tili'), ('eng', 'Ingliz tili')], default='uz', max_length=10, verbose_name='Til'),
        ),
    ]
