# Generated by Django 6.0.2 on 2026-02-27 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='Filial nomi')),
                ('city', models.CharField(max_length=155, verbose_name='Shaxar')),
                ('address', models.TextField(blank=True, null=True, verbose_name="To'liq adress")),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiallar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_code', models.CharField(max_length=300, unique=True, verbose_name='Inventar raqami')),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('borrowed', 'Borrowed'), ('lost', 'Lost')], default='available', max_length=30)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nusxalar', to='catalog.book')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filialkitoblar', to='circulation.branch')),
            ],
            options={
                'verbose_name': 'Kitob nusxasi',
                'verbose_name_plural': 'Kitob nusxalari',
            },
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_at', models.DateTimeField(auto_now_add=True, verbose_name='Olingan vaqt')),
                ('due_at', models.DateTimeField(verbose_name='Muddati')),
                ('returned_at', models.DateTimeField(blank=True, verbose_name='Qaytarilgan vaqt')),
                ('fine_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='Jarima miqdori')),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitob', to='circulation.bookcopy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_book', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Qarz',
                'verbose_name_plural': 'Qarzlar',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20, verbose_name='Xolati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('expires_at', models.DateTimeField(verbose_name='Tugaydigan vaqti')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='catalog.book')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='circulation.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bron',
                'verbose_name_plural': 'Bronlar',
            },
        ),
    ]
